version: 0.2

phases:
  install:
    runtime-versions:
    java: corretto17
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes